# Site settings
title: Philway's oj
email: lvsummer.fly@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    oj practice-To solve all of oj'problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oj.philway.me" # the base hostname & protocol for your site
twitter_username: philway 
github_username: philway 

# Build settings
markdown: kramdown
